<?xml version="1.0" encoding="UTF-8"?>

<!-- Unos programadores necesitan estructurar la información que intercambiarán los ficheros de sus aplicaciones
 para lo cual han determinado los requisitos siguientes.
Los ficheros deben tener un elemento <listafacturas>
Dentro de la lista debe haber una o más facturas.
Las facturas tienen un atributo fecha que es optativo.
Toda factura tiene un emisor, que es un elemento obligatorio y que debe tener un atributo cif que es obligatorio. 
Dentro de emisor debe haber un elemento nombre, que es obligatorio y puede o no haber un elemento volumenventas.
Toda factura debe tener un elemento pagador, el cual tiene exactamente la misma estructura que emisor.
Toda factura tiene un elemento importe-->

<!DOCTYPE listafacturas[
<!ELEMENT listafacturas (factura+)>

<!ELEMENT factura (emisor, pagador, importe)>
<!ATTLIST factura fecha CDATA #IMPLIED >

<!ELEMENT emisor (nombreE, volumenventasE?)>
<!ELEMENT nombreE (#PCDATA)>
<!ELEMENT volumenventasE (#PCDATA) >
<!ATTLIST emisor cif CDATA #REQUIRED > <!-- Obligatorio-->
<!ELEMENT pagador (nombrePagador, volumenVentasPagador?) >
<!ELEMENT nombrePagador (#PCDATA) >
<!ELEMENT volumenVentasPagador (#PCDATA)>
<!ELEMENT importe (#PCDATA)>
<!ATTLIST pagador cif CDATA #REQUIRED >
]>

<listafacturas>
    <factura fecha="01-05-23">
    
        <emisor cif="1487">
            <nombreE>Maria,Mario</nombreE>
            <volumenventasE>200</volumenventasE>
        </emisor>
        <pagador cif="1599">
            <nombrePagador>Maria, Luis,Mario</nombrePagador>
            <volumenVentasPagador>250</volumenVentasPagador>
        </pagador>
        <importe>500</importe>

    </factura>
</listafacturas>