<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca[

    <!ELEMENT biblioteca (producto+)>
    <!ELEMENT producto (nombre, autor*, fecha, caracteristicas)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT autor (#PCDATA)>
    <!ELEMENT fecha (dia, mes, a単o)?>
    <!ELEMENT dia (#PCDATA)>
    <!ELEMENT mes (#PCDATA)>
    <!ELEMENT a単o (#PCDATA)>
    <!ELEMENT caracteristicas (caracteristica+)>
    <!ELEMENT caracteristica (#PCDATA)>
    ]>

<biblioteca>
<producto>
        <nombre>Fundacion</nombre>

        <autor>Elisa</autor>

        <fecha> 
            <dia>20</dia>
            <mes>09</mes>
            <a単o>2022</a単o>
        </fecha>

    <caracteristicas>
    
            <caracteristica nombre = "pagninas">160</caracteristica>
            <caracteristica nombre = "color">negro</caracteristica>
            <caracteristica nombre = "precio">50</caracteristica>
            <caracteristica nombre = "genero">historia</caracteristica>
            
    </caracteristicas>
        
        
</producto>
</biblioteca>