=== STEMgranada/Marcas/xml6.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="listaCursos">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="curso" minOccurs = "1" maxOccurs = "unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="listaAlumnos">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="alumno" minOccurs = "1" maxOccurs = "20">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="DNI" type="xs:string"></xs:element>
                                                <xs:element name="nombre" type="xs:string"></xs:element>
                                                <xs:element name="primerApellido" type="xs:string"></xs:element>
                                                <xs:element name="segundoApellido" type="xs:string" minOccurs = "0" maxOccurs = "1"></xs:element>
                                                <xs:element name="listaAsignaturas">
                                                    <xs:complexType>
                                                        <xs:sequence>
                                                            <xs:element name="asignatura" minOccurs = "1" maxOccurs = "6">
                                                                <xs:complexType>
                                                                    <xs:sequence>

                                                                        <xs:element name="nombre">
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:string">
                                                                                    <xs:enumeration value="Programacion"/>
                                                                                    <xs:enumeration value="Bases de Datos"/>
                                                                                    <xs:enumeration value="FOL"/>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:element>

                                                                        <xs:element name="horasSemanales">
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:integer">
                                                                                    <xs:minInclusive value="1"></xs:minInclusive>
                                                                                    <xs:maxInclusive value="10"></xs:maxInclusive>
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:element>

                                                                        <xs:element name="profesor">
                                                                            <xs:complexType>
                                                                                <xs:sequence>
                                                                                    <xs:element name="NRP" type="xs:string"></xs:element>
                                                                                    <xs:element name="nombre" type="xs:string"></xs:element>
                                                                                    <xs:element name="primerApellido" type="xs:string"></xs:element>
                                                                                    <xs:element name="segundoApellido" type="xs:string" minOccurs = "0" maxOccurs = "1"></xs:element>
                                                                                </xs:sequence>
                                                                            </xs:complexType>
                                                                        </xs:element>
                                                                    </xs:sequence>
                                                                    <xs:attribute name="codigo" type="xs:string"/>
                                                                </xs:complexType>
                                                            </xs:element>
                                                        </xs:sequence>
                                                    </xs:complexType>
                                                </xs:element>
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>
</xs:element>
</xs:schema>

=== STEMgranada/Marcas/xml6.xml
<?xml version="1.0" encoding="UTF-8"?>

<!-- Un instituto necesita registrar los cursos y alumnos que estudian en él 
y necesita comprobar los documentos XML de los programas que utiliza:
Tiene que haber un elemento raíz listacursos. Tiene que haber uno o más 
cursos.
Un curso tiene uno o más alumnos (máximo 20)
Todo alumno tiene un DNI, un nombre y un apellido, puede que tenga 
segundo apellido o no.
Un alumno escoge una lista de asignaturas donde habrá una o más 
asignaturas (máximo 6). 
Toda asignatura tiene un nombre (Solo se permiten las asignaturas 
Programación, Bases de Datos y FOL), un atributo código,
 un profesor y las horas semanales (un número entero entre 1 y 10).
Un profesor tiene un NRP (Número de Registro Personal), un nombre 
y un apellido (también puede tener o no un segundo apellido).-->

<listaCursos xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:noNamespaceSchemaLocation="xml6.xsd">
    <curso>
        <listaAlumnos>
            <alumno>
                <DNI></DNI>
                <nombre></nombre>
                <primerApellido></primerApellido>
                <segundoApellido></segundoApellido>
                <listaAsignaturas>
                    <asignatura codigo="1234">
                        <nombre>Programacion</nombre>
                        <horasSemanales>9</horasSemanales>
                        <profesor>
                            <NRP></NRP>
                            <nombre></nombre>
                            <primerApellido></primerApellido>
                            <segundoApellido></segundoApellido>
                        </profesor>
                    </asignatura>
                </listaAsignaturas>
            </alumno>
        </listaAlumnos>
    </curso>
</listaCursos>
